version: '3.8'

services:
  public_leak_scanner:
    build: .
    container_name: public_leak_scanner
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/
    volumes:
      - .:/app
    command: python main.py

  mongodb:
    image: mongo:latest
    container_name: mongodb
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
